# Generated by Django 4.2.30 on 2026-08-23

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=120)),
                ("kind", models.CharField(choices=[("CURRENT", "Current account")], max_length=32)),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("parser_version", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("PROCESSING", "Processing"), ("ACCEPTED", "Accepted"), ("PARTIAL", "Partial"), ("REJECTED", "Rejected"), ("FATAL", "Fatal"), ("DUPLICATE", "Duplicate")], max_length=16)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sheet_alias", models.CharField(blank=True, max_length=16, null=True)),
                ("worksheet_name", models.CharField(blank=True, max_length=255, null=True)),
                ("worksheet_ordinal", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("parsed_count", models.PositiveIntegerField(default=0)),
                ("ignored_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("reconciliation_status", models.CharField(blank=True, choices=[("RECONCILED", "Reconciled"), ("NOT_RECONCILED", "Not reconciled"), ("INSUFFICIENT_DATA", "Insufficient data"), ("NOT_APPLICABLE", "Not applicable")], max_length=24, null=True)),
                ("opening_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("ending_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("reconciliation_difference", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("failure_stage", models.CharField(blank=True, choices=[("PARSER", "Parser"), ("PERSISTENCE", "Persistence"), ("BOUNDARY", "Boundary")], max_length=16, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("occurrence_date", models.DateField()),
                ("signed_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("description", models.TextField(blank=True, null=True)),
                ("source_reference", models.TextField(blank=True, null=True)),
                ("running_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("amount_source_column", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("row_number", models.PositiveIntegerField()),
                ("raw_cells", models.JSONField()),
                ("row_class", models.CharField(choices=[("metadata", "Metadata"), ("movement_candidate", "Movement candidate"), ("header", "Header"), ("blank", "Blank"), ("auxiliary", "Auxiliary")], max_length=32)),
                ("parse_outcome", models.CharField(choices=[("PARSED", "Parsed"), ("IGNORED", "Ignored"), ("REJECTED", "Rejected")], max_length=8)),
                ("parser_codes", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="SourceArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_kind", models.CharField(choices=[("SANTANDER_CURRENT_ACCOUNT_XLSX", "Santander current-account XLSX")], max_length=64)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_digest", models.CharField(max_length=64, unique=True)),
                ("content", models.BinaryField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(model_name="rawrecord", name="import_batch", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="raw_records", to="ledger.importbatch")),
        migrations.AddField(model_name="movement", name="account", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="ledger.account")),
        migrations.AddField(model_name="movement", name="raw_record", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="movement", to="ledger.rawrecord")),
        migrations.AddField(model_name="importbatch", name="account", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ledger.account")),
        migrations.AddField(model_name="importbatch", name="duplicate_of", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="duplicate_attempts", to="ledger.importbatch")),
        migrations.AddField(model_name="importbatch", name="source_artifact", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ledger.sourceartifact")),
        migrations.AddConstraint(model_name="account", constraint=models.CheckConstraint(check=models.Q(("currency__regex", "^[A-Z]{3}$")), name="account_currency_iso_like")),
        migrations.AddConstraint(model_name="sourceartifact", constraint=models.CheckConstraint(check=models.Q(("content_digest__regex", "^[0-9a-f]{64}$")), name="artifact_sha256_hex")),
        migrations.AddConstraint(model_name="rawrecord", constraint=models.UniqueConstraint(fields=("import_batch", "row_number"), name="one_raw_record_per_batch_row")),
        migrations.AddConstraint(model_name="rawrecord", constraint=models.CheckConstraint(check=models.Q(("row_number__gt", 0)), name="raw_record_positive_row")),
        migrations.AddConstraint(model_name="rawrecord", constraint=models.CheckConstraint(check=models.Q(("parse_outcome__in", ["PARSED", "IGNORED", "REJECTED"])), name="raw_record_outcome_known")),
        migrations.AddIndex(model_name="movement", index=models.Index(fields=["account", "occurrence_date"], name="movement_account_date_idx")),
        migrations.AddConstraint(model_name="movement", constraint=models.CheckConstraint(check=models.Q(("signed_amount", 0), _negated=True), name="movement_signed_amount_nonzero")),
        migrations.AddConstraint(model_name="movement", constraint=models.CheckConstraint(check=models.Q(("currency__regex", "^[A-Z]{3}$")), name="movement_currency_iso_like")),
        migrations.AddConstraint(model_name="movement", constraint=models.CheckConstraint(check=models.Q(("amount_source_column__in", ["E", "F"])), name="movement_amount_column_known")),
        migrations.AddConstraint(model_name="importbatch", constraint=models.CheckConstraint(check=models.Q(("status__in", ["PROCESSING", "ACCEPTED", "PARTIAL", "REJECTED", "FATAL", "DUPLICATE"])), name="batch_status_known")),
        migrations.AddConstraint(model_name="importbatch", constraint=models.CheckConstraint(check=models.Q(models.Q(("completed_at__isnull", True), ("status", "PROCESSING")), models.Q(("completed_at__isnull", False), ("status__in", ["ACCEPTED", "PARTIAL", "REJECTED", "FATAL", "DUPLICATE"])), _connector="OR"), name="batch_completion_matches_status")),
        migrations.AddConstraint(model_name="importbatch", constraint=models.CheckConstraint(check=models.Q(models.Q(("duplicate_of__isnull", False), ("status", "DUPLICATE")), models.Q(("duplicate_of__isnull", True), ("status__in", ["PROCESSING", "ACCEPTED", "PARTIAL", "REJECTED", "FATAL"])), _connector="OR"), name="batch_duplicate_reference_matches_status")),
        migrations.AddConstraint(model_name="importbatch", constraint=models.CheckConstraint(check=models.Q(models.Q(("failure_code__isnull", False), ("failure_stage__isnull", False), ("status", "FATAL")), models.Q(("failure_code__isnull", True), ("failure_stage__isnull", True), ("status__in", ["PROCESSING", "ACCEPTED", "PARTIAL", "REJECTED", "DUPLICATE"])), _connector="OR"), name="batch_failure_fields_match_status")),
        migrations.AddConstraint(model_name="importbatch", constraint=models.CheckConstraint(check=models.Q(("period_start__isnull", True), ("period_end__isnull", True), ("period_start__lte", models.F("period_end")), _connector="OR"), name="batch_period_order")),
        migrations.AddConstraint(model_name="importbatch", constraint=models.CheckConstraint(check=models.Q(models.Q(("reconciliation_status__isnull", True), ("status", "PROCESSING")), models.Q(("reconciliation_status__isnull", True), ("status", "FATAL")), models.Q(("reconciliation_status__isnull", True), ("status", "DUPLICATE")), models.Q(("reconciliation_status__isnull", False), ("status__in", ["ACCEPTED", "PARTIAL", "REJECTED"])), _connector="OR"), name="batch_reconciliation_matches_status")),
        migrations.AddConstraint(model_name="importbatch", constraint=models.UniqueConstraint(condition=models.Q(("status__in", ["ACCEPTED", "PARTIAL", "REJECTED"])), fields=("source_artifact", "account"), name="one_materialized_batch_per_artifact_account")),
    ]
