# Generated by Django 4.2.30 on 2026-08-23

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):
    dependencies = [("ledger", "0001_initial")]

    operations = [
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                check=Q(parsed_count__gte=0) & Q(ignored_count__gte=0) & Q(rejected_count__gte=0),
                name="batch_counts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                check=(
                    Q(status="ACCEPTED", rejected_count=0)
                    | Q(status="PARTIAL", parsed_count__gt=0, rejected_count__gt=0)
                    | Q(status="REJECTED", parsed_count=0, rejected_count__gt=0)
                    | Q(status="FATAL", parsed_count=0, ignored_count=0, rejected_count=0)
                    | Q(status="DUPLICATE", parsed_count=0, ignored_count=0, rejected_count=0)
                    | Q(status="PROCESSING")
                ),
                name="batch_counts_match_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                check=Q(duplicate_of__isnull=True) | ~Q(duplicate_of=F("id")),
                name="batch_duplicate_not_self",
            ),
        ),
    ]
