# Generated by Django 4.2.30 on 2026-08-23

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [("ledger", "0002_importbatch_batch_counts_nonnegative_and_more")]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="source_variant",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                check=Q(source_variant__isnull=True) | ~Q(source_variant=""),
                name="batch_source_variant_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                check=(
                    Q(status__in=["PROCESSING", "FATAL"])
                    | Q(
                        status__in=["ACCEPTED", "PARTIAL", "REJECTED", "DUPLICATE"],
                        source_variant__isnull=False,
                    )
                ),
                name="batch_source_variant_matches_status",
            ),
        ),
    ]
