# Generated by Django 4.2.30 on 2026-08-23

from django.db import migrations, models
from django.db.models import Q


def backfill_account_orientation(apps, schema_editor):
    Account = apps.get_model("ledger", "Account")
    unexpected_kinds = set(
        Account.objects.exclude(kind="CURRENT").values_list("kind", flat=True).distinct()
    )
    if unexpected_kinds:
        kinds = ", ".join(sorted(unexpected_kinds))
        raise RuntimeError(f"Cannot backfill Account economic orientation for kinds: {kinds}")
    Account.objects.filter(kind="CURRENT").update(economic_orientation="ASSET")


class Migration(migrations.Migration):
    dependencies = [("ledger", "0003_importbatch_source_variant")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="economic_orientation",
            field=models.CharField(
                blank=True,
                choices=[("ASSET", "Asset"), ("LIABILITY", "Liability")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_account_orientation, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="account",
            name="economic_orientation",
            field=models.CharField(
                choices=[("ASSET", "Asset"), ("LIABILITY", "Liability")],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CURRENT", "Current account"),
                    ("CREDIT_CARD", "Credit card"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                check=(
                    Q(kind="CURRENT", economic_orientation="ASSET")
                    | Q(kind="CREDIT_CARD", economic_orientation="LIABILITY")
                ),
                name="account_kind_orientation_known",
            ),
        ),
    ]
