# Generated by Django 4.2.30 on 2026-09-05 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


def guard_reverse_classification(apps, schema_editor):
    models_to_remove = [
        apps.get_model('ledger', name)
        for name in ('Category', 'MovementClassification')
    ]
    # Keep the emptiness check and table removal exclusive until commit.
    tables = ', '.join(
        schema_editor.quote_name(model._meta.db_table) for model in models_to_remove
    )
    schema_editor.execute(f'LOCK TABLE {tables} IN ACCESS EXCLUSIVE MODE')
    if any(model.objects.using(schema_editor.connection.alias).exists()
           for model in models_to_remove):
        raise RuntimeError('Cannot reverse classification migration while classification data exists.')


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_demo_synthetic_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovementClassification',
            fields=[
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='classification', serialize=False, to='ledger.movement')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual')], max_length=16)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), name='category_display_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('display_name', ''), _negated=True), name='category_display_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='movementclassification',
            constraint=models.CheckConstraint(check=models.Q(('source', 'MANUAL')), name='classification_source_manual'),
        ),
        migrations.AddConstraint(
            model_name='movementclassification',
            constraint=models.CheckConstraint(check=models.Q(('revision__gte', 1)), name='classification_revision_positive'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse_classification),
    ]
